### ISSUE TITLE
Found some bug Win 10 Latest Python

### ISSUE THREAD

**Issue by Nitish2048** [FeezyHendrix/Insta-mass-account-creator#101]
Traceback (most recent call last):
  File "E:\Users\nitis\Desktop\Insta-mass-account-creator-master\creator.py", line 3, in <module>
    from modules.requestbot import runBot
  File "E:\Users\nitis\Desktop\Insta-mass-account-creator-master\modules\requestbot.py", line 99
    except Exceptionas e:
                       ^
SyntaxError: invalid syntax

Using Win 10 An cofig is : 

"""
    author: feezyhendrix

    Configuration files
    NOTE: check Assets/proxies.txt to use your custom proxies.
 """
import os

import logging

logging.basicConfig(level=logging.INFO)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSET_DIR = os.path.join(BASE_DIR, 'Assets' )

Config = {
    "bot_type" : 2, #change to 2 to use python requests
    "use_custom_proxy" : True, #default is False change to True to use a file containing multiple proxies of yours.
    "use_local_ip_address" : False, #default is False chnage to True to user your computers ip directly.
    "amount_of_account": 10, #amount of account you want to create make sure it doesnt exceed 50 for better performance
    "amount_per_proxy": 2, #this would be amont of account used if you have a you are using multiple proxies
    "proxy_file_path" : ASSET_DIR + "/proxies.txt",
    "email_domain": "gmail.com",
    "country": "in",
    "activation_email_addr": "**********@gmail.com",
    "activation_email_pass": "********",
    "activation_email_serv": "pop.gmail.com",
    "activation_email_spor": 995,
}

**Comment by vocabexpresshaxer** [comment]
Change line 99 in requestbot.py

From: except Exceptionas e:
To: except Exception as e:

Looks like you or the developer deleted a space accidentally
