### ISSUE TITLE
while running creator.py

### ISSUE THREAD

**Issue by muhdameen** [FeezyHendrix/Insta-mass-account-creator#174]
Traceback (most recent call last):
  File "F:\Insta-mass-account-creator-master\Insta-mass-account-creator-master\creator.py", line 2, in <module>
    from modules.seleniumbot import runbot
  File "F:\Insta-mass-account-creator-master\Insta-mass-account-creator-master\modules\seleniumbot.py", line 11, in <module>
    import modules.generateaccountinformation as accnt
  File "F:\Insta-mass-account-creator-master\Insta-mass-account-creator-master\modules\generateaccountinformation.py", line 8, in <module>
    import mechanicalsoup
ModuleNotFoundError: No module named 'mechanicalsoup'

**Comment by security-hm** [comment]
> Traceback (most recent call last):
> File "F:\Insta-mass-account-creator-master\Insta-mass-account-creator-master\creator.py", line 2, in
> from modules.seleniumbot import runbot
> File "F:\Insta-mass-account-creator-master\Insta-mass-account-creator-master\modules\seleniumbot.py", line 11, in
> import modules.generateaccountinformation as accnt
> File "F:\Insta-mass-account-creator-master\Insta-mass-account-creator-master\modules\generateaccountinformation.py", line 8, in
> import mechanicalsoup
> ModuleNotFoundError: No module named 'mechanicalsoup'

open cmd and run this command line:
`python -m pip install MechanicalSoup`

**Comment by InputEngineer20** [comment]
" No module named pip "

What can I do ?

**Comment by security-hm** [comment]
> " No module named pip "
> 
> What can I do ?

## For Linux: 
`apt install python3-pip`

## For Windows:
[https://phoenixnap.com/kb/install-pip-windows](windows)
