### ISSUE TITLE
bitta help here

### ISSUE THREAD

**Issue by MasterPanda61** [FeezyHendrix/Insta-mass-account-creator#175]
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Python38\lib\site-packages\urllib3\connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Python38\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Python38\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\320eldrluke\AppData\Roaming\Python\Python38\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Python38\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.sslproxies.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "creator.py", line 12, in <module>
    accountCreator()
  File "creator.py", line 7, in accountCreator
    runbot()
  File "C:\Users\320eldrluke\Downloads\reddit\Insta-mass-account-creator-master\Insta-mass-account-creator-master\modules\seleniumbot.py", line 200, in runbot
    account = AccountCreator(config.Config['use_custom_proxy'], config.Config['use_local_ip_address'])
  File "C:\Users\320eldrluke\Downloads\reddit\Insta-mass-account-creator-master\Insta-mass-account-creator-master\modules\seleniumbot.py", line 32, in __init__
    self.__collect_sockets()
  File "C:\Users\320eldrluke\Downloads\reddit\Insta-mass-account-creator-master\Insta-mass-account-creator-master\modules\seleniumbot.py", line 36, in __collect_sockets
    r = requests.get("https://www.sslproxies.org/")
  File "C:\Users\320eldrluke\AppData\Roaming\Python\Python38\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\320eldrluke\AppData\Roaming\Python\Python38\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\320eldrluke\AppData\Roaming\Python\Python38\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\320eldrluke\AppData\Roaming\Python\Python38\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\320eldrluke\AppData\Roaming\Python\Python38\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.sslproxies.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)')))

**Comment by Schlingelkron** [comment]
I wouldnt recommend using it anymore. Its outdated and not being maintended by anyone. 
Also its using selenium with a webdriver wich is most of the time detected by instagram these days, its better to use requests, its faster and not detectable.

**Comment by ronitdalal** [comment]
Please help me How to do this 🥲🥲🥲🥺😢

**Comment by filipmasek** [comment]
Hi, Schlingelkron.
I see that you know how it works and what is effective way of doing this.. i dont want to use those prebuilded apps.. i want to learn it and do by myself because i am a few years in programming. 
I would be grateful if you would give me some contact on you. I can pay you for some lessons or help if you have time and you would be so kind.

Could contact me on:
masek-filip@email.cz
