### ISSUE TITLE
creator.py

### ISSUE THREAD

**Issue by Anhabyr** [FeezyHendrix/Insta-mass-account-creator#189]
Microsoft Windows [Version 10.0.19044.1706]
(c) Microsoft Corporation. All rights reserved.

C:\Users\anhaa\Desktop\Insta-mass-account-creator-master>py creator.py
Traceback (most recent call last):
  File "C:\Users\anhaa\Desktop\Insta-mass-account-creator-master\creator.py", line 2, in <module>
    from modules.seleniumbot import runbot
  File "C:\Users\anhaa\Desktop\Insta-mass-account-creator-master\modules\seleniumbot.py", line 11, in <module>
    import modules.generateaccountinformation as accnt
  File "C:\Users\anhaa\Desktop\Insta-mass-account-creator-master\modules\generateaccountinformation.py", line 8, in <module>
    import mechanicalsoup
ModuleNotFoundError: No module named 'mechanicalsoup'

C:\Users\anhaa\Desktop\Insta-mass-account-creator-master>

**Comment by alanfranciscobr** [comment]
just install the module. "pip install mechanicalsoup" (without quotes)
