### ISSUE TITLE
Unable to run botcore.py

### ISSUE THREAD

**Issue by rudyrection** [FeezyHendrix/Insta-mass-account-creator#3]
Hello,

I am getting a syntax error when trying to run botcore.py. Do you know what's going on?
`(virt) dhcp-206-87-121-13:insta jhaw$ python botcore.py
Traceback (most recent call last):
  File "botcore.py", line 13, in <module>
    from modules.storeusernametofirebase import storeinfirebase
  File "/Users/jhaw/Desktop/insta/modules/storeusernametofirebase.py", line 1, in <module>
    from firebase import firebase
  File "/Users/jhaw/Desktop/virt/lib/python3.7/site-packages/firebase/__init__.py", line 3
    from .async import process_pool
              ^
SyntaxError: invalid syntax`

**Comment by FeezyHendrix** [comment]
Did you correctly configure your config file.

**Comment by rudyrection** [comment]
Yes I believe so, for input_generate password I put by firebase login password is this correct?
Also, what format is the proxy in?
IP:PORT:USERNAME:Password? Or is it something else.

**Comment by FeezyHendrix** [comment]
Well, the password field is a general password for the accounts you are creating.

**Comment by rudyrection** [comment]
I filled in the config.py correctly. But I am still getting syntax error

`(insta-mass) Jackys-MacBook-Pro-2:insta jhaw$ python3.7 botcore.py
Traceback (most recent call last):
  File "botcore.py", line 14, in <module>
    from modules.storeusernametofirebase import storeinfirebase
  File "/Users/jhaw/Desktop/insta/modules/storeusernametofirebase.py", line 1, in <module>
    from firebase import firebase
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/firebase/__init__.py", line 3
    from .async import process_pool`

**Comment by rudyrection** [comment]
Now I am getting this:
`(env) Jackys-MacBook-Pro-2:insta jhaw$ python3.6 botcore.py
Traceback (most recent call last):
  File "botcore.py", line 17, in <module>
    driver = webdriver.Chrome(chrome_options)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1258, in _execute_child
    executable = os.fsencode(executable)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/os.py", line 800, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not Options`

**Comment by FeezyHendrix** [comment]
This issue has been fixed kindly re clone the new repo
