### ISSUE TITLE
ModuleNotFoundError: No module named 'getIdentity'

### ISSUE THREAD

**Issue by Toinou974** [FeezyHendrix/Insta-mass-account-creator#56]
I keep receiving this error : 

```
Traceback (most recent call last):
  File "creator.py", line 2, in <module>
    from modules.seleniumbot import runbot
  File "C:\Users\toino\Desktop\creator\modules\seleniumbot.py", line 11, in <module>
    import modules.generateaccountinformation as accnt
  File "C:\Users\toino\Desktop\creator\modules\generateaccountinformation.py", line 13, in <module>
    from getIdentity import getRandomIdentity
ModuleNotFoundError: No module named 'getIdentity'
```

**Comment by ARKRafay** [comment]
After I removed the HEAD code. I'm getting this same error too

**Comment by TAnas0** [comment]
This seems like an import syntax error.

Modify the import line to (note the point):
```python
from .getIdentity import getRandomIdentity
```
If you face other import error message for local files, making the path relative by appending may solve it

**Comment by WindsofRose** [comment]
in this bot very much sintax misstakes...

**Comment by bambanggr** [comment]
> 
> 
> This seems like an import syntax error.
> 
> Modify the import line to (note the point):
> 
> ```python
> from .getIdentity import getRandomIdentity
> ```
> 
> If you face other import error message for local files, making the path relative by appending may solve it

i changed the code as you said and found new issues : 
`ModuleNotFoundError: No module named 'activate_account'`
