### ISSUE TITLE
HELP SOS

### ISSUE THREAD

**Issue by r4x171** [FeezyHendrix/Insta-mass-account-creator#63]
python3 creator.py 
Traceback (most recent call last):
  File "creator.py", line 12, in <module>
    accountCreator()
  File "creator.py", line 9, in accountCreator
    runBot()
  File "/cyber/Insta-mass-account-creator/modules/requestbot.py", line 96, in runBot
    account_info = new_account(country=Config['country'])
TypeError: new_account() got an unexpected keyword argument 'country'

**Comment by peerdenhoed** [comment]
I have the same problem 
$ python creator.py
Traceback (most recent call last):
  File "creator.py", line 12, in <module>
    accountCreator()
  File "creator.py", line 9, in accountCreator
    runBot()
  File "C:\Users\peerd\Insta-mass-account-creator\modules\requestbot.py", line 95, in runBot
    account_info = new_account(country=Config['Germany'])
KeyError: 'Germany'



$ python creator.py
Traceback (most recent call last):
  File "creator.py", line 12, in <module>
    accountCreator()
  File "creator.py", line 9, in accountCreator
    runBot()
  File "C:\Users\peerd\Insta-mass-account-creator\modules\requestbot.py", line 95, in runBot
    account_info = new_account(country=Config['Random'])
KeyError: 'Random'



$ python creator.py
Traceback (most recent call last):
  File "creator.py", line 12, in <module>
    accountCreator()
  File "creator.py", line 9, in accountCreator
    runBot()
  File "C:\Users\peerd\Insta-mass-account-creator\modules\requestbot.py", line 95, in runBot
    account_info = new_account(country=Config['country'])
TypeError: new_account() got an unexpected keyword argument 'country'


$ python creator.py
Traceback (most recent call last):
  File "creator.py", line 12, in <module>
    accountCreator()
  File "creator.py", line 9, in accountCreator
    runBot()
  File "C:\Users\peerd\Insta-mass-account-creator\modules\requestbot.py", line 95, in runBot
    account_info = new_account(country=Config['Belgium'])
KeyError: 'Belgium'


It's driving me crazy!!
