### ISSUE TITLE
Can't run - syntax error

### ISSUE THREAD

**Issue by DaemonGFX** [FeezyHendrix/Insta-mass-account-creator#68]
I have setup chromedriver and installed all requirements but when I do python creator.py I get this: 
C:\Users\Daemon\Desktop\Insta-mass-account-creator-master>python creator.py
Traceback (most recent call last):
  File "creator.py", line 3, in <module>
    from modules.requestbot import runBot
  File "C:\Users\Daemon\Desktop\Insta-mass-account-creator-master\modules\requestbot.py", line 89
    except:
         ^
SyntaxError: invalid syntax

Using Windows 10
Thanks

**Comment by Nitish2048** [comment]
Same Issue with me
