### ISSUE TITLE
i Have this problem !!!!! help

### ISSUE THREAD

**Issue by halperdz** [FeezyHendrix/Insta-mass-account-creator#71]
`  Traceback (most recent call last):
  File "C:\Users\yacer\instamass2\insta\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\yacer\instamass2\insta\lib\site-packages\urllib3\connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "C:\Users\yacer\instamass2\insta\lib\site-packages\urllib3\connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "C:\Users\yacer\instamass2\insta\lib\site-packages\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "C:\Users\yacer\instamass2\insta\lib\site-packages\urllib3\util\ssl_.py", line 325, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "c:\users\yacer\appdata\local\programs\python\python37-32\Lib\ssl.py", line 412, in wrap_socket
    session=session
  File "c:\users\yacer\appdata\local\programs\python\python37-32\Lib\ssl.py", line 853, in _create
    self.do_handshake()
  File "c:\users\yacer\appdata\local\programs\python\python37-32\Lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\yacer\instamass2\insta\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\yacer\instamass2\insta\lib\site-packages\urllib3\connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\yacer\instamass2\insta\lib\site-packages\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\yacer\instamass2\insta\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
File "C:\Users\yacer\instamass2\insta\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\yacer\instamass2\insta\lib\site-packages\urllib3\connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "C:\Users\yacer\instamass2\insta\lib\site-packages\urllib3\connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "C:\Users\yacer\instamass2\insta\lib\site-packages\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "C:\Users\yacer\instamass2\insta\lib\site-packages\urllib3\util\ssl_.py", line 325, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "c:\users\yacer\appdata\local\programs\python\python37-32\Lib\ssl.py", line 412, in wrap_socket
    session=session
  File "c:\users\yacer\appdata\local\programs\python\python37-32\Lib\ssl.py", line 853, in _create
    self.do_handshake()
  File "c:\users\yacer\appdata\local\programs\python\python37-32\Lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(0, 'Error'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "creator.py", line 12, in <module>
    accountCreator()
  File "creator.py", line 7, in accountCreator
    runbot()
  File "C:\Users\yacer\instamass2\insta\instamass\modules\seleniumbot.py", line 189, in runbot
    account = AccountCreator(config.Config['use_custom_proxy'], config.Config['use_local_ip_address'])
  File "C:\Users\yacer\instamass2\insta\instamass\modules\seleniumbot.py", line 32, in __init__
    self.__collect_sockets()
  File "C:\Users\yacer\instamass2\insta\instamass\modules\seleniumbot.py", line 36, in __collect_sockets
    r = requests.get("https://www.sslproxies.org/")
  File "C:\Users\yacer\instamass2\insta\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\yacer\instamass2\insta\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\yacer\instamass2\insta\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\yacer\instamass2\insta\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\yacer\instamass2\insta\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error'))`

**Comment by halperdz** [comment]
problem fixed
