### ISSUE TITLE
Cannot import name 'Imap'

### ISSUE THREAD

**Issue by InstantlyMoist** [FeezyHendrix/Insta-mass-account-creator#74]
The bot creator is not working. 

`Traceback (most recent call last):
  File "creator.py", line 2, in <module>
    from modules.seleniumbot import runbot
  File "D:\Insta-mass-account-creator-master\Insta-mass-account-creator-master\modules\seleniumbot.py", line 13, in <module>
    from .activate_account import get_activation_url
  File "D:\Insta-mass-account-creator-master\Insta-mass-account-creator-master\modules\activate_account.py", line 6, in <module>
    from pymailutils import Imap, Email
ImportError: cannot import name 'Imap'`

Not sure what I should do about this.

Using the default config.

**Comment by RIPLIK** [comment]
ImportError: cannot import name Imap .  (((((((((
