### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by LefyMakesPie** [FeezyHendrix/Insta-mass-account-creator#76]
**Describe the bug**
When i tried installing it i typed in pip install -r requirements.txt and it gave me a error called ERROR: Could not find a version that satisfies the requirement pymailutils==0.1 (from -r requirements.txt (line 8)) (from versions: none)
ERROR: No matching distribution found for pymailutils==0.1 (from -r requirements.txt (line 8))

**Screenshots**
http://prntscr.com/nsxlyy

 - OS: Windows
 - Browser: Chrome,

**Comment by LefyMakesPie** [comment]
When i try running the creator in python it gives me this Traceback (most recent call last):
  File "C:\Users\Orestas\Desktop\New folder\Insta-mass-account-creator-master\creator.py", line 2, in <module>
    from modules.seleniumbot import runbot
  File "C:\Users\Orestas\Desktop\New folder\Insta-mass-account-creator-master\modules\seleniumbot.py", line 11, in <module>
    import modules.generateaccountinformation as accnt
  File "C:\Users\Orestas\Desktop\New folder\Insta-mass-account-creator-master\modules\generateaccountinformation.py", line 8, in <module>
    import mechanicalsoup
ModuleNotFoundError: No module named 'mechanicalsoup'

**Comment by SlevinGee** [comment]
i  get the same error for the requirements

**Comment by t0malbrecht** [comment]
As stated in #72 
"You need to use the proper git URL: https://github.com/matteogaito/pymailutils

pip install git+git://github.com/matteogaito/pymailutils.git

or

pip install git+https://github.com/matteogaito/pymailutils.git

Also see the VCS Support section of the pip documentation."
