### ISSUE TITLE
ModuleNotFoundError: No module named 'mechanicalsoup'

### ISSUE THREAD

**Issue by matej2** [FeezyHendrix/Insta-mass-account-creator#78]
**Describe the bug**
I cloned repo and tried to run the app. When i run `python creator.py`, it returns me this error: 

```
ModuleNotFoundError: No module named 'mechanicalsoup
```

**To Reproduce**
1. Settings in `config.py`: Leave them as they are (default)
4. See error:

```
Traceback (most recent call last):
  File "creator.py", line 2, in <module>
    from modules.seleniumbot import runbot
  File "Insta-mass-account-creator\modules\seleniumbot.py", line 11, in <module>
    import modules.generateaccountinformation as accnt
  File "Insta-mass-account-creator\modules\generateaccountinformation.py", line 8, in <module>
    import mechanicalsoup
ModuleNotFoundError: No module named 'mechanicalsoup'
```

**Expected behavior**
The app sould run

**Screenshots**
See error text above

 - OS: Windows 10
 - Browser Chrome

**Additional context**
/

**Comment by mgurdogan** [comment]
Install pip then install Mechanicalsoup,


`pip install MechanicalSoup`

**Comment by matej2** [comment]
Isnt this already in `requirements.txt`? The question is why it does not detect it...

**Comment by kris4oo** [comment]
Traceback (most recent call last):
  File "creator.py", line 2, in <module>
    from modules.seleniumbot import runbot
  File "C:\Users\User\Desktop\Insta-mass-account-creator-master\modules\seleniumbot.py", line 11, in <module>
    import modules.generateaccountinformation as accnt
  File "C:\Users\User\Desktop\Insta-mass-account-creator-master\modules\generateaccountinformation.py", line 8, in <module>
    import mechanicalsoup
ImportError: No module named mechanicalsoup

Mine problem. I think its kinda the same

**Comment by FeezyHendrix** [comment]
Try creating a virtual environment and install the dependencies on it.

**Comment by matej2** [comment]
Do you mean docker virtual machine?

**Comment by FeezyHendrix** [comment]
https://docs.python.org/3/library/venv.html pythons virtualenv for proper management of packages.

**Comment by amrography** [comment]
Try this solution
https://github.com/googlesamples/assistant-sdk-python/issues/236#issuecomment-383039470

**Comment by muhdameen** [comment]
pip install MechanicalSoup
pip install selenium
python creator.py
