### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by dark3bod** [FeezyHendrix/Insta-mass-account-creator#84]
python creator.py
Traceback (most recent call last):
  File "creator.py", line 12, in <module>
    accountCreator()
  File "creator.py", line 9, in accountCreator
    runBot()
  File "C:\Users\M\Desktop\Insta-mass-account-creator-master\modules\requestbot.py", line 97, in runBot
    account_info = new_account(country=Config['country'])
TypeError: new_account() got an unexpected keyword argument 'country'

**Comment by FeezyHendrix** [comment]
You need to add the country in your config.
