### ISSUE TITLE
Requestbot.py 

### ISSUE THREAD

**Issue by Incredible9042** [FeezyHendrix/Insta-mass-account-creator#87]
Traceback (most recent call last):
  File "creator.py", line 3, in <module>
    from modules.requestbot import runBot
  File "C:\Users\אריאל\Desktop\Insta-mass-account-creator-master\modules\requestbot.py", line 99
    except Exceptionas e:
                       ^
SyntaxError: invalid syntax

**Comment by organ108** [comment]
should be "except Exception as e:"
